### ISSUE TITLE
Run executable with Parameters in normal and silent mode.

### ISSUE THREAD

**Issue by SirKrlos** [hahouari/inno_bundle#9]
**Is your feature request related to a problem? Please describe.**
1) Running '.exe' with parameters in both normal and silent mode is not supported.
ie:
- MyInstaller.exe /silent
- MyInstaller.exe /verysilent

2) Running '.exe' with parameters in both normal and silent mode is not supported.
ie:
- Normal mode: MyProgram.exe --after-installer
- Silent mode: MyProgram.exe --after-silent-installer

**Describe the solution you'd like**
As mentioned in the previous section, it would be a feature that I need for my project, so I can identify when the executable was started by the installer and in what mode (normal or silent), in addition to running the project when my automatic installer run the installer in silent mode.

**Describe alternatives you've considered**
I was able to do this manually, but each time the installer is created, the .iss file is remade, making it impossible to do it this way. I also didn't find any other lib for flutter with this feature.

**Additional context**
Example definition in pubspec.yaml file:
![image](https://github.com/user-attachments/assets/6a4a507a-8cf2-41eb-8228-58378e37cc14)

**Comment by hahouari** [comment]
I have answered this on [this issue comment](https://github.com/hahouari/inno_bundle/pull/10#issuecomment-2473638581).

I designed the package in the first place to allow devs to create installers with moderate customization and without the need to learn ISS scripting, I really suggest (since you arrived to the point of writing ISS code) to just add an ISS script along with your git repo project instead of using a package like `inno_bundle` that could limit you instead of helping you.

Even better, you could just install your fork in  your pubspec.yaml using [this stack overflow answer](https://stackoverflow.com/a/54023220).

I wish you best of luck.
